version: '3'
services:
  web:
    build: .
    ports:
      - '3001:3001'
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    links:
      - db
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017
  db:
    image: mongo
    restart: always
